name: OTA JSON Updater

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git

      - name: Ensure talkman.json exists
        run: |
          [ -f talkman.json ] || echo '{"response":[]}' > talkman.json

      - name: Fetch releases and update JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 18.1
          ROMTYPE: UNOFFICIAL
        run: |
          # Fetch releases JSON
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" > releases.json

          # Read old JSON safely
          OLD_JSON=$(cat talkman.json)

          # Build new entries safely
          NEW_JSON=$(jq --arg version "$VERSION" --arg romtype "$ROMTYPE" '
            # input: releases.json
            map((.assets // [])[] | select(.name | test("-talkman.zip$")) |
              {
                datetime: (now|floor),
                filename: .name,
                id: "",  # SHA256 placeholder
                romtype: $romtype,
                size: .size,
                url: ("https://github.com/'"${GITHUB_REPOSITORY}"'/releases/download/" + .name + "/" + .name),
                version: $version,
                changelog: ""
              }
            )
          ' releases.json)

          # Merge old + new, skipping duplicates
          echo "$OLD_JSON" | jq --argjson new "$NEW_JSON" '
            .response = (.response // []) + ($new | map(select(.filename as $f | (.response[]? | .filename != $f))))
          ' > tmp.json

          mv tmp.json talkman.json

      - name: Commit updated talkman.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add talkman.json
          git commit -m "Update talkman.json from GitHub Release(s) [skip ci]" || echo "No changes to commit"
          git push
