name: OTA JSON Updater

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git

      - name: Ensure talkman.json exists
        run: |
          [ -f talkman.json ] || echo '{"response":[]}' > talkman.json

      - name: Update talkman.json from releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JSON_FILE: talkman.json
          VERSION: 18.1
          ROMTYPE: UNOFFICIAL
        run: |
          # Fetch releases
          RELEASES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")

          # Build new JSON entries in one jq pass
          jq --arg version "$VERSION" \
             --arg romtype "$ROMTYPE" \
             --argjson now "$(date +%s)" \
             --slurpfile existing "$JSON_FILE" '
             # Start with existing response
             .response = ($existing[0].response // []) +
             (
               $RELEASES | 
               map(.assets[]? | select(.name | test("-talkman.zip$")) |
                 {
                   datetime: ($now | tonumber),
                   filename: .name,
                   id: "",          # Placeholder, can compute SHA256 separately
                   romtype: $romtype,
                   size: .size,
                   url: ("https://github.com/'"${GITHUB_REPOSITORY}"'/releases/download/" + .name + "/" + .name),
                   version: $version,
                   changelog: ""
                 })
             )
          ' --argjson RELEASES "$RELEASES" talkman.json > tmp.json && mv tmp.json talkman.json

      - name: Commit updated talkman.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add talkman.json
          git commit -m "Update talkman.json from GitHub Release(s) [skip ci]" || echo "No changes to commit"
          git push
